/* Generated By:JavaCC: Do not edit this line. ManifestParserConstants.java */
package tmp.generated_manifest;

public interface ManifestParserConstants {

  int EOF = 0;
  int ALPHANUM = 1;
  int HEADERCHAR = 2;
  int OTHER = 3;
  int SPACE = 4;
  int EXPORTPACKAGE = 5;
  int NAME = 6;
  int COLON = 7;
  int VALUE = 8;
  int NEWLINE = 9;
  int LINEBREAK = 10;
  int COMMA = 12;
  int PACKAGEDCL = 13;
  int PACKAGEEND = 14;

  int DEFAULT = 0;
  int PACKAGE = 1;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<HEADERCHAR>",
    "<OTHER>",
    "\" \"",
    "\"Export-Package: \"",
    "<NAME>",
    "\":\"",
    "<VALUE>",
    "<NEWLINE>",
    "<LINEBREAK>",
    "\" \"",
    "\",\"",
    "<PACKAGEDCL>",
    "<PACKAGEEND>",
    "\",\"",
  };

}
