/* Generated By:JavaCC: Do not edit this line. HaskellParser.java */
package tmp.generated_phaskell;

import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;

  public class HaskellParser implements HaskellParserConstants {

        /**
	 * Append the given {@link Token} and any preceding special tokens to a
	 * given {@link StringBuffer}.
	 * 
	 * @param token
	 *            the given JavaCC {@link Token} object
	 * @param buffer
	 *            the buffer to which to append <code>token</code>
	 */
        final private static void accumulate(Token token, StringBuffer buffer) {

                // Append preceding special tokens to <code>buffer</code>:
                //
                Token special = firstSpecial(token);
                if (special != token)
                        while (special != null) {
                                buffer.append(special.toString());
                                special = special.next;
                        }

                // Finally, append the token itself:
                //
                buffer.append(token.toString());
        }

        /**
	 * Accumulate {@list Token} objects from the token stream, respecting nested
	 * code inside <code>open</code> and <code>close</code> pairs, until an
	 * unmatched <code>close</code> is the next token in the stream. This
	 * method assumes that an <code>open</code> token has just been read from
	 * the stream so the initial nesting level is 1. The method returns when a
	 * matching <code>close</code> token is the next token in the token
	 * stream. <em>The <code>close</code> token is left in the stream!</em>
	 * 
	 * @return the accumulated tokens as a {@link String}.
	 * 
	 * @throws ParseException
	 *             if an end-of-file is found before an unmatched
	 *             <code>close</code> token.
	 */
        final private Token accumulateNestedRegion(int open, int close)
                        throws ParseException {

                StringBuffer buffer = new StringBuffer();
                Token token = getToken(1);

                // Initialize result with known information (starting position, etc.):
                //
                Token result = Token.newToken(UNANTICIPATED_SYMBOL);
                result.specialToken = null;

                Token startToken = firstSpecial(token);
                result.beginColumn = startToken.beginColumn;
                result.beginLine = startToken.beginLine;
                result.offset=startToken.offset;

                // Accumulate tokens until a <code>close</code> token is found:
                //
                for (int nesting = 1; nesting > 0;) {


                        if (token.kind == EOF)
                                throw new ParseException("accumulating from line "
                                                + result.beginLine + " at column " + result.beginColumn
                                                + ": EOF reached before ending " + tokenImage[close]
                                                + " found");

                        if (token.kind == open)
                                ++nesting;
                        else if (token.kind == close) {
                                if (nesting == 1)
                                        break;
                                --nesting;
                        }

                        // Update information in result:
                        //
                        result.endColumn = token.endColumn;
                        result.endLine = token.endLine;
                        result.length=(token.offset-result.offset)+token.length;
                        result.next = token.next;

                        accumulate(token, buffer);
                        getNextToken();
                        token = getToken(1);
                }

                result.image = buffer.toString();
                return result;
        }


        final private Token accumulateUntil(boolean considerInnerBlocks,
                        int endTokenKind) throws ParseException {
                return accumulateUntil(considerInnerBlocks, new int[] { endTokenKind });
        }

        final private Token accumulateUntil(boolean considerInnerBlocks,
                        int endTokenKind1, int endTokenKind2) throws ParseException {
                return accumulateUntil(considerInnerBlocks, new int[] { endTokenKind1,
                                endTokenKind2 });
        }

        final private Token accumulateUntil(boolean considerInnerBlocks,
                        int endTokenKind1, int endTokenKind2, int endTokenKind3)
                        throws ParseException {
                return accumulateUntil(considerInnerBlocks, new int[] { endTokenKind1,
                                endTokenKind2, endTokenKind3 });
        }
        final private Token accumulateUntil(boolean considerInnerBlocks,
                        int endTokenKind1, int endTokenKind2, int endTokenKind3, int endTokenKind4)
                        throws ParseException {
                return accumulateUntil(considerInnerBlocks, new int[] { endTokenKind1,
                                endTokenKind2, endTokenKind3, endTokenKind4 });
        }

        final private boolean isNot(int kind) {
                return getToken(1).kind != kind;
        }

        final private boolean isNot(int k1, int k2) {
                return isNot(k1) && isNot(k2);
        }

        final private boolean isNot(int k1, int k2, int k3) {
                return isNot(k1, k2) && isNot(k3);
        }
        final private boolean isNot(int k1, int k2, int k3, int k4) {
                return isNot(k1, k2, k3) && isNot(k4);
        }

        /** returns true if the CONTEXT_ARROW is found before the SEMICOLON **/
        final private boolean isContext() throws ParseException {
                int lookahead=1;
                while (true) {
                        Token t = getToken(lookahead);
                        if (t.kind==EOF) throw new ParseException("EOF found before ; or =>  (line " + token.beginLine
                                                + ", column " + token.beginColumn
                                                + ")");
                        if (t.kind==SEMICOLON) return false;
                        if (t.kind==CONTEXT_ARROW) return true;
                        lookahead++;
                }
        }

        /**
	 * Accumulate {@link Token} objects from the token stream until a token
	 * matching <code>tokenKind</code> is consumed from the stream. The tokens
	 * are accumulated in <code>buffer</code>, NOT including the terminating
	 * token.
	 * 
	 * @return a {@link Token} formed by concatenating all intervening tokens
	 *         and special tokens.
	 */
        final private Token accumulateUntil(boolean considerInnerBlocks,
                        int[] endTokenKinds) throws ParseException {

                StringBuffer buffer = new StringBuffer();
                Token token = getToken(1);

                // Initialize result with known information (starting position, etc.):
                //
                Token result = Token.newToken(UNANTICIPATED_SYMBOL);
                result.specialToken = null;

                Token startToken = firstSpecial(token);
                result.beginColumn = startToken.beginColumn;
                result.beginLine = startToken.beginLine;
                result.offset=startToken.offset;

                // Accumulate tokens until a <code>tokenKind</code> token is found:
                //
                int nesting=0;
                while (!contains(endTokenKinds, token.kind) || nesting >0) {
                        // Update information in result:
                        //
                        result.endColumn = token.endColumn;
                        result.endLine = token.endLine;
                        result.next = token.next;
                        result.length=(token.offset-result.offset)+token.length;

                        if (token.kind == EOF)
                                throw new ParseException("from line " + result.beginLine
                                                + " at column " + result.beginColumn
                                                + ": EOF reached before " + images(endTokenKinds)
                                                + " found");

                        if (considerInnerBlocks && token.kind == LEFT_CURLY)
                                ++nesting;
                        else if (considerInnerBlocks && token.kind == RIGHT_CURLY) {
                                --nesting;
                        }

                        accumulate(token, buffer);
                        getNextToken();
                        token = getToken(1);
                }

                if (buffer.length() == 0)
                        throw new ParseException("syntax error - empty pseudo-match (line " + result.beginLine
                                                + ", column " + result.beginColumn
                                                + ")");

                result.image = buffer.toString();
                return result;
        }

        private String images(int[] endTokenKinds) {
                String result = "";
                for (int i : endTokenKinds)
                        result += tokenImage[i] + " ";
                return result;
        }

        private boolean contains(int[] endTokenKinds, int kind) {
                for (int i : endTokenKinds)
                        if (i == kind)
                                return true;
                return false;
        }

    /**
     * Finds the first token, special or otherwise, in the list of special
     * tokens preceding this {@link Token}.  If this list is non-empty, the
     * result will be a special token.  Otherwise, it will be the starting
     * token.
     *
     * @param token the given {@link Token}.
     * @return the first special token preceding <code>token</code>.
     **/
    final private static Token firstSpecial (Token token) {

        while (token.specialToken != null)
            token = token.specialToken ;

        return token ;
    }

  Token findListContent() throws ParseException {
    return accumulateNestedRegion(LEFT_PAREN, RIGHT_PAREN) ;
  }

  Token findBlockContent() throws ParseException {
    return accumulateNestedRegion (LEFT_CURLY, RIGHT_CURLY) ;
  }

  Token findConRest() throws ParseException {
        //(block | ~(SEMICOLON|ALT|RIGHT_CURLY))*
    return accumulateUntil(true,SEMICOLON,ALT,RIGHT_CURLY,DERIVING) ;
  }

  Token findNonstddeclRest() throws ParseException {
        //(block | ~(SEMICOLON|RIGHT_CURLY))+
    return accumulateUntil(true,SEMICOLON,RIGHT_CURLY) ;
  }

  Token findUntilSemiOrCCB() throws ParseException {
        //~(SEMICOLON | RIGHT_CURLY)*
    return accumulateUntil(false,SEMICOLON,RIGHT_CURLY) ;
  }

  Token findUntilSemiOrContextArrow() throws ParseException {
        //(~(CONTEXT_ARROW|SEMICOLON))*;
    return accumulateUntil(false,CONTEXT_ARROW,SEMICOLON) ;
  }

  Token findUntilSemiOrEquals() throws ParseException {
        //~(EQUALS|SEMICOLON))*
    return accumulateUntil(false,SEMICOLON,EQUALS) ;
  }

  Token findUntilEquals() throws ParseException {
        //~(EQUALS))*
    return accumulateUntil(false,EQUALS) ;
  }

  final public module module() throws ParseException {
        modid modid;
        exports exports = null;
        body body;
        Token t;
        ASTStringNode eof;
        Token firstToken=token;
    jj_consume_token(MODULE);
    modid = modid();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEFT_PAREN:
      exports = exports();
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    jj_consume_token(WHERE);
    body = body();
    t = jj_consume_token(0);
                                                                               eof=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new module(modid, exports, body, eof, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public qconid qconid() throws ParseException {
        Token t;
        ASTStringNode constructor_id;
        Token firstToken=token;
    t = jj_consume_token(CONSTRUCTOR_ID);
                           constructor_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new qconid(constructor_id, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public exports exports() throws ParseException {
        exportsList exportsList = null;
        ASTTextNode text364 = null;
        Token firstToken=token;
    jj_consume_token(LEFT_PAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MODULE:
    case CONSTRUCTOR_ID:
    case VARIABLE_ID:
    case LEFT_PAREN:
      exportsList = exportsList();
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
                                              text364=new ASTTextNode(",",new WToken(token));
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(RIGHT_PAREN);
         {if (true) return new exports(exportsList, text364, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public exportsList exportsList() throws ParseException {
        export export;
        ArrayList<export> list0=new ArrayList<export>();
        export export1;
        ArrayList<export> export1List = new ArrayList<export>();
        Token firstToken=token;
    export = export();
                        list0.add(export);
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_1;
      }
      jj_consume_token(COMMA);
      export1 = export();
                                                                               list0.add(export1);
    }
         {if (true) return new exportsList(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public export export() throws ParseException {
        qvar qvar;
        qtyconorcls qtyconorcls;
        details details = null;
        modid modid;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARIABLE_ID:
    case LEFT_PAREN:
      qvar = qvar();
         {if (true) return new export1(qvar, firstToken.next,token);}
      break;
    case CONSTRUCTOR_ID:
      qtyconorcls = qtyconorcls();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT_PAREN:
        details = details();
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
         {if (true) return new export2(qtyconorcls, details, firstToken.next,token);}
      break;
    case MODULE:
      jj_consume_token(MODULE);
      modid = modid();
         {if (true) return new export3(modid, firstToken.next,token);}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public details details() throws ParseException {
        Token t;
        ASTStringNode varsym;
        cnamelist cnamelist = null;
        Token firstToken=token;
    if (jj_2_2(2)) {
      jj_consume_token(LEFT_PAREN);
      t = jj_consume_token(VARSYM);
                                    varsym=new ASTStringNode(t.image,new WToken(t));
      jj_consume_token(RIGHT_PAREN);
         {if (true) return new details1(varsym, firstToken.next,token);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT_PAREN:
        jj_consume_token(LEFT_PAREN);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CONSTRUCTOR_ID:
        case VARIABLE_ID:
          cnamelist = cnamelist();
          break;
        default:
          jj_la1[5] = jj_gen;
          ;
        }
        jj_consume_token(RIGHT_PAREN);
         {if (true) return new details2(cnamelist, firstToken.next,token);}
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public cnamelist cnamelist() throws ParseException {
        cname cname;
        ArrayList<cname> list0=new ArrayList<cname>();
        cname cname1;
        ArrayList<cname> cname1List = new ArrayList<cname>();
        Token firstToken=token;
    cname = cname();
                      list0.add(cname);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      cname1 = cname();
                                                             list0.add(cname1);
    }
         {if (true) return new cnamelist(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public qtyconorcls qtyconorcls() throws ParseException {
        qconid qconid;
        Token firstToken=token;
    qconid = qconid();
         {if (true) return new qtyconorcls(qconid, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public cname cname() throws ParseException {
        Token t;
        ASTStringNode variable_id;
        ASTStringNode constructor_id;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARIABLE_ID:
      t = jj_consume_token(VARIABLE_ID);
                        variable_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new cname1(variable_id, firstToken.next,token);}
      break;
    case CONSTRUCTOR_ID:
      t = jj_consume_token(CONSTRUCTOR_ID);
                           constructor_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new cname2(constructor_id, firstToken.next,token);}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public qvar qvar() throws ParseException {
        qvarid qvarid;
        qvarsym qvarsym;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARIABLE_ID:
      qvarid = qvarid();
         {if (true) return new qvar1(qvarid, firstToken.next,token);}
      break;
    case LEFT_PAREN:
      jj_consume_token(LEFT_PAREN);
      qvarsym = qvarsym();
      jj_consume_token(RIGHT_PAREN);
         {if (true) return new qvar2(qvarsym, firstToken.next,token);}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public qvarid qvarid() throws ParseException {
        Token t;
        ASTStringNode variable_id;
        Token firstToken=token;
    t = jj_consume_token(VARIABLE_ID);
                        variable_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new qvarid(variable_id, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public qvarsym qvarsym() throws ParseException {
        Token t;
        ASTStringNode varsym;
        Token firstToken=token;
    t = jj_consume_token(VARSYM);
                   varsym=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new qvarsym(varsym, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public modid modid() throws ParseException {
        qconid qconid;
        Token firstToken=token;
    qconid = qconid();
         {if (true) return new modid(qconid, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public conid conid() throws ParseException {
        Token t;
        ASTStringNode constructor_id;
        Token firstToken=token;
    t = jj_consume_token(CONSTRUCTOR_ID);
                           constructor_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new conid(constructor_id, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public body body() throws ParseException {
        impdecls impdecls;
        topdecls topdecls = null;
        topdecls topdecls1;
        Token firstToken=token;
    if (jj_2_3(2)) {
      jj_consume_token(LEFT_CURLY);
      impdecls = impdecls();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        jj_consume_token(SEMICOLON);
        topdecls = topdecls();
        break;
      default:
        jj_la1[10] = jj_gen;
        ;
      }
      jj_consume_token(RIGHT_CURLY);
         {if (true) return new body1(impdecls, topdecls, firstToken.next,token);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT_CURLY:
        jj_consume_token(LEFT_CURLY);
        topdecls1 = topdecls();
        jj_consume_token(RIGHT_CURLY);
         {if (true) return new body2(topdecls1, firstToken.next,token);}
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public impdecls impdecls() throws ParseException {
        impdecl impdecl;
        ArrayList<impdecl> list0=new ArrayList<impdecl>();
        impdecl impdecl1;
        ArrayList<impdecl> impdecl1List = new ArrayList<impdecl>();
        Token firstToken=token;
    impdecl = impdecl();
                          list0.add(impdecl);
    label_3:
    while (true) {
      if (jj_2_4(2)) {
        ;
      } else {
        break label_3;
      }
      jj_consume_token(SEMICOLON);
      impdecl1 = impdecl();
                                                                                    list0.add(impdecl1);
    }
         {if (true) return new impdecls(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public impdecl impdecl() throws ParseException {
        ASTTextNode text366 = null;
        modid modid;
        modid modid1 = null;
        impspec impspec = null;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IMPORT:
      jj_consume_token(IMPORT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUALIFIED:
        jj_consume_token(QUALIFIED);
                               text366=new ASTTextNode("qualified",new WToken(token));
        break;
      default:
        jj_la1[12] = jj_gen;
        ;
      }
      modid = modid();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AS:
        jj_consume_token(AS);
        modid1 = modid();
        break;
      default:
        jj_la1[13] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case HIDING:
      case LEFT_PAREN:
        impspec = impspec();
        break;
      default:
        jj_la1[14] = jj_gen;
        ;
      }
         {if (true) return new impdecl1(text366, modid, modid1, impspec, firstToken.next,token);}
      break;
    default:
      jj_la1[15] = jj_gen;
         {if (true) return new impdecl2(firstToken.next,token);}
    }
    throw new Error("Missing return statement in function");
  }

  final public impspec impspec() throws ParseException {
        ASTTextNode text368 = null;
        imports imports = null;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HIDING:
      jj_consume_token(HIDING);
                   text368=new ASTTextNode("hiding",new WToken(token));
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    jj_consume_token(LEFT_PAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTRUCTOR_ID:
    case VARIABLE_ID:
    case LEFT_PAREN:
      imports = imports();
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(RIGHT_PAREN);
         {if (true) return new impspec(text368, imports, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public imports imports() throws ParseException {
        imp imp;
        imp imp1;
        ArrayList<imp> imp1List = new ArrayList<imp>();
        Token firstToken=token;
    imp = imp();
    label_4:
    while (true) {
      if (jj_2_5(2147483647)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(COMMA);
      imp1 = imp();
                                                       imp1List.add(imp1);
    }
         {if (true) return new imports(imp, imp1List, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public imp imp() throws ParseException {
        var var;
        tyconorcls tyconorcls;
        list list = null;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARIABLE_ID:
    case LEFT_PAREN:
      var = var();
         {if (true) return new imp1(var, firstToken.next,token);}
      break;
    case CONSTRUCTOR_ID:
      tyconorcls = tyconorcls();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT_PAREN:
        list = list();
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
         {if (true) return new imp2(tyconorcls, list, firstToken.next,token);}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public tyconorcls tyconorcls() throws ParseException {
        conid conid;
        Token firstToken=token;
    conid = conid();
         {if (true) return new tyconorcls(conid, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public topdecls topdecls() throws ParseException {
        topdecl topdecl;
        ArrayList<topdecl> list0=new ArrayList<topdecl>();
        topdecl topdecl1;
        ArrayList<topdecl> topdecl1List = new ArrayList<topdecl>();
        Token firstToken=token;
    topdecl = topdecl();
                          list0.add(topdecl);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_5;
      }
      jj_consume_token(SEMICOLON);
      topdecl1 = topdecl();
                                                                       list0.add(topdecl1);
    }
         {if (true) return new topdecls(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public topdecl topdecl() throws ParseException {
        simpletype simpletype;
        declrhs declrhs;
        optContext optContext;
        simpletype simpletype1;
        constrs constrs;
        deriving deriving = null;
        optContext optContext1;
        simpletype simpletype2;
        declrhs declrhs1;
        optContext optContext2;
        conid conid;
        tyvar tyvar;
        cdecls cdecls = null;
        optContext optContext3;
        qconid qconid;
        inst inst;
        block block = null;
        list list;
        decl decl;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPE:
      jj_consume_token(TYPE);
      simpletype = simpletype();
      declrhs = declrhs();
         {if (true) return new typedecl(simpletype, declrhs, firstToken.next,token);}
      break;
    case DATA:
      jj_consume_token(DATA);
      optContext = optContext();
      simpletype1 = simpletype();
      jj_consume_token(EQUALS);
      constrs = constrs();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DERIVING:
        deriving = deriving();
        break;
      default:
        jj_la1[21] = jj_gen;
        ;
      }
         {if (true) return new datadecl(optContext, simpletype1, constrs, deriving, firstToken.next,token);}
      break;
    case NEWTYPE:
      jj_consume_token(NEWTYPE);
      optContext1 = optContext();
      simpletype2 = simpletype();
      declrhs1 = declrhs();
         {if (true) return new newtypedecl(optContext1, simpletype2, declrhs1, firstToken.next,token);}
      break;
    case CLASS:
      jj_consume_token(CLASS);
      optContext2 = optContext();
      conid = conid();
      tyvar = tyvar();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHERE:
        jj_consume_token(WHERE);
        cdecls = cdecls();
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
         {if (true) return new classdecl(optContext2, conid, tyvar, cdecls, firstToken.next,token);}
      break;
    case INSTANCE:
      jj_consume_token(INSTANCE);
      optContext3 = optContext();
      qconid = qconid();
      inst = inst();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHERE:
        jj_consume_token(WHERE);
        block = block();
        break;
      default:
        jj_la1[23] = jj_gen;
        ;
      }
         {if (true) return new instancedecl(optContext3, qconid, inst, block, firstToken.next,token);}
      break;
    case DEFAULTTOKEN:
      jj_consume_token(DEFAULTTOKEN);
      list = list();
         {if (true) return new defaultdecl(list, firstToken.next,token);}
      break;
    default:
      jj_la1[24] = jj_gen;
      decl = decl();
         {if (true) return new declaration(decl, firstToken.next,token);}
    }
    throw new Error("Missing return statement in function");
  }

  final public decl decl() throws ParseException {
        signdecl signdecl;
        fixdecl fixdecl;
        valdef valdef;
        nonstddecl nonstddecl;
        Token firstToken=token;
    if (jj_2_6(2147483647)) {
      signdecl = signdecl();
         {if (true) return new typeSignature(signdecl, firstToken.next,token);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INFIXL:
      case INFIXR:
      case INFIX:
        fixdecl = fixdecl();
         {if (true) return new fixityDeclaration(fixdecl, firstToken.next,token);}
        break;
      default:
        jj_la1[25] = jj_gen;
        if (jj_2_7(2147483647)) {
          valdef = valdef();
         {if (true) return new valueDeclaration(valdef, firstToken.next,token);}
        } else {
          nonstddecl = nonstddecl();
         {if (true) return new nonStandardDeclaration(nonstddecl, firstToken.next,token);}
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public declrhs declrhs() throws ParseException {
        Token t;
        ASTStringNode findnonstddeclrest = null;
        Token firstToken=token;
    jj_consume_token(EQUALS);
    if (isNot(SEMICOLON,RIGHT_CURLY)) {
      t = findNonstddeclRest();
                                                                              findnonstddeclrest=new ASTStringNode(t.image,new WToken(t));
    } else {
      ;
    }
         {if (true) return new declrhs(findnonstddeclrest, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public optContext optContext() throws ParseException {
        context context = null;
        Token firstToken=token;
    if (isContext()) {
      context = context();
      jj_consume_token(CONTEXT_ARROW);
    } else {
      ;
    }
         {if (true) return new optContext(context, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public deriving deriving() throws ParseException {
        Token t;
        ASTStringNode findnonstddeclrest;
        Token firstToken=token;
    jj_consume_token(DERIVING);
    t = findNonstddeclRest();
                                          findnonstddeclrest=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new deriving(findnonstddeclrest, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public constrs constrs() throws ParseException {
        constr constr;
        ArrayList<constr> list0=new ArrayList<constr>();
        constr constr1;
        ArrayList<constr> constr1List = new ArrayList<constr>();
        Token firstToken=token;
    constr = constr();
                        list0.add(constr);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ALT:
        ;
        break;
      default:
        jj_la1[26] = jj_gen;
        break label_6;
      }
      jj_consume_token(ALT);
      constr1 = constr();
                                                                  list0.add(constr1);
    }
         {if (true) return new constrs(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public constr constr() throws ParseException {
        conP conP;
        Token t;
        ASTStringNode findconrest = null;
        Token firstToken=token;
    conP = conP();
    if (isNot(SEMICOLON,ALT,RIGHT_CURLY,DERIVING)) {
      t = findConRest();
                                                                                            findconrest=new ASTStringNode(t.image,new WToken(t));
    } else {
      ;
    }
         {if (true) return new constr(conP, findconrest, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public inst inst() throws ParseException {
        gtycon gtycon;
        gtycon gtycon1;
        tyvar tyvar;
        ArrayList<tyvar> tyvarList = new ArrayList<tyvar>();
        conid conid;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTRUCTOR_ID:
      gtycon = gtycon();
         {if (true) return new inst1(gtycon, firstToken.next,token);}
      break;
    case LEFT_PAREN:
      jj_consume_token(LEFT_PAREN);
      gtycon1 = gtycon();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VARIABLE_ID:
          ;
          break;
        default:
          jj_la1[27] = jj_gen;
          break label_7;
        }
        tyvar = tyvar();
                                            tyvarList.add(tyvar);
      }
      jj_consume_token(RIGHT_PAREN);
         {if (true) return new inst2(gtycon1, tyvarList, firstToken.next,token);}
      break;
    case LEFT_BRACKET:
      jj_consume_token(LEFT_BRACKET);
      conid = conid();
      jj_consume_token(RIGHT_BRACKET);
         {if (true) return new inst3(conid, firstToken.next,token);}
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public gtycon gtycon() throws ParseException {
        qtyconorcls qtyconorcls;
        Token firstToken=token;
    qtyconorcls = qtyconorcls();
         {if (true) return new gtycon(qtyconorcls, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public cdecls cdecls() throws ParseException {
        cdeclsI cdeclsI = null;
        Token firstToken=token;
    jj_consume_token(LEFT_CURLY);
    cdeclsI = cdeclsI();
    jj_consume_token(RIGHT_CURLY);
         {if (true) return new cdecls(cdeclsI, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public cdeclsI cdeclsI() throws ParseException {
        cdecl cdecl;
        ArrayList<cdecl> list0=new ArrayList<cdecl>();
        cdecl cdecl1;
        ArrayList<cdecl> cdecl1List = new ArrayList<cdecl>();
        Token firstToken=token;
    cdecl = cdecl();
                      list0.add(cdecl);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[29] = jj_gen;
        break label_8;
      }
      jj_consume_token(SEMICOLON);
      cdecl1 = cdecl();
                                                             list0.add(cdecl1);
    }
         {if (true) return new cdeclsI(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public cdecl cdecl() throws ParseException {
        signdecl signdecl;
        nonstddecl nonstddecl;
        Token firstToken=token;
    if (jj_2_8(2147483647)) {
      signdecl = signdecl();
         {if (true) return new cdecl1(signdecl, firstToken.next,token);}
    } else {
      nonstddecl = nonstddecl();
         {if (true) return new cdecl2(nonstddecl, firstToken.next,token);}
    }
    throw new Error("Missing return statement in function");
  }

  final public context context() throws ParseException {
        Token t;
        ASTStringNode finduntilsemiorcontextarrow = null;
        Token firstToken=token;
    if (isNot(SEMICOLON,CONTEXT_ARROW)) {
      t = findUntilSemiOrContextArrow();
                                                                                     finduntilsemiorcontextarrow=new ASTStringNode(t.image,new WToken(t));
    } else {
      ;
    }
         {if (true) return new context(finduntilsemiorcontextarrow, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public simpletype simpletype() throws ParseException {
        Token t;
        ASTStringNode constructor_id;
        ASTStringNode finduntilequals = null;
        Token firstToken=token;
    t = jj_consume_token(CONSTRUCTOR_ID);
                           constructor_id=new ASTStringNode(t.image,new WToken(t));
    if (isNot(EQUALS)) {
      t = findUntilEquals();
                                                                                                                                     finduntilequals=new ASTStringNode(t.image,new WToken(t));
    } else {
      ;
    }
         {if (true) return new simpletype(constructor_id, finduntilequals, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public nonstddecl nonstddecl() throws ParseException {
        Token t;
        ASTStringNode findnonstddeclrest;
        Token firstToken=token;
    t = findNonstddeclRest();
                               findnonstddeclrest=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new nonstddecl(findnonstddeclrest, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public valdef valdef() throws ParseException {
        funlhs funlhs;
        declrhs declrhs;
        Token firstToken=token;
    funlhs = funlhs();
    declrhs = declrhs();
         {if (true) return new valdef(funlhs, declrhs, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public fixdecl fixdecl() throws ParseException {
        fixity fixity;
        Token t;
        ASTStringNode integer = null;
        ops ops;
        Token firstToken=token;
    fixity = fixity();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER:
      t = jj_consume_token(INTEGER);
                                     integer=new ASTStringNode(t.image,new WToken(t));
      break;
    default:
      jj_la1[30] = jj_gen;
      ;
    }
    ops = ops();
         {if (true) return new fixdecl(fixity, integer, ops, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public fixity fixity() throws ParseException {
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INFIXL:
      jj_consume_token(INFIXL);
         {if (true) return new fixity1(firstToken.next,token);}
      break;
    case INFIXR:
      jj_consume_token(INFIXR);
         {if (true) return new fixity2(firstToken.next,token);}
      break;
    case INFIX:
      jj_consume_token(INFIX);
         {if (true) return new fixity3(firstToken.next,token);}
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ops ops() throws ParseException {
        op op;
        ArrayList<op> list0=new ArrayList<op>();
        op op1;
        ArrayList<op> op1List = new ArrayList<op>();
        Token firstToken=token;
    op = op();
                list0.add(op);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[32] = jj_gen;
        break label_9;
      }
      jj_consume_token(COMMA);
      op1 = op();
                                              list0.add(op1);
    }
         {if (true) return new ops(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public signdecl signdecl() throws ParseException {
        vars vars;
        Token t;
        ASTStringNode finduntilsemiorccb = null;
        Token firstToken=token;
    vars = vars();
    jj_consume_token(OFTYPE);
    if (isNot(SEMICOLON,RIGHT_CURLY)) {
      t = findUntilSemiOrCCB();
                                                                                           finduntilsemiorccb=new ASTStringNode(t.image,new WToken(t));
    } else {
      ;
    }
         {if (true) return new signdecl(vars, finduntilsemiorccb, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public vars vars() throws ParseException {
        var var;
        ArrayList<var> list0=new ArrayList<var>();
        var var1;
        ArrayList<var> var1List = new ArrayList<var>();
        Token firstToken=token;
    var = var();
                  list0.add(var);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_10;
      }
      jj_consume_token(COMMA);
      var1 = var();
                                                   list0.add(var1);
    }
         {if (true) return new vars(list0, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public var var() throws ParseException {
        Token t;
        ASTStringNode variable_id;
        ASTStringNode varsym;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARIABLE_ID:
      t = jj_consume_token(VARIABLE_ID);
                        variable_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new var1(variable_id, firstToken.next,token);}
      break;
    case LEFT_PAREN:
      jj_consume_token(LEFT_PAREN);
      t = jj_consume_token(VARSYM);
                       varsym=new ASTStringNode(t.image,new WToken(t));
      jj_consume_token(RIGHT_PAREN);
         {if (true) return new var2(varsym, firstToken.next,token);}
      break;
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public conP conP() throws ParseException {
        Token t;
        ASTStringNode constructor_id;
        ASTStringNode consym;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTRUCTOR_ID:
      t = jj_consume_token(CONSTRUCTOR_ID);
                           constructor_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new conP1(constructor_id, firstToken.next,token);}
      break;
    case LEFT_PAREN:
      jj_consume_token(LEFT_PAREN);
      t = jj_consume_token(CONSYM);
                       consym=new ASTStringNode(t.image,new WToken(t));
      jj_consume_token(RIGHT_PAREN);
         {if (true) return new conP2(consym, firstToken.next,token);}
      break;
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public tyvar tyvar() throws ParseException {
        Token t;
        ASTStringNode variable_id;
        Token firstToken=token;
    t = jj_consume_token(VARIABLE_ID);
                        variable_id=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new tyvar(variable_id, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public funlhs funlhs() throws ParseException {
        funlhsL funlhsL;
        funlhsR funlhsR = null;
        Token firstToken=token;
    funlhsL = funlhsL();
    if (isNot(SEMICOLON,EQUALS,LEFT_CURLY)) {
      funlhsR = funlhsR();
    } else {
      ;
    }
         {if (true) return new funlhs(funlhsL, funlhsR, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public funlhsL funlhsL() throws ParseException {
        Token t;
        ASTStringNode variable_id;
        varop varop;
        var var;
        Token firstToken=token;
    if (jj_2_9(2147483647)) {
      t = jj_consume_token(VARIABLE_ID);
                                                         variable_id=new ASTStringNode(t.image,new WToken(t));
      varop = varop();
         {if (true) return new funlhsL1(variable_id, varop, firstToken.next,token);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VARIABLE_ID:
      case LEFT_PAREN:
        var = var();
         {if (true) return new funlhsL2(var, firstToken.next,token);}
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public funlhsR funlhsR() throws ParseException {
        block block;
        Token t;
        ASTStringNode finduntilsemiorequals;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEFT_CURLY:
      block = block();
         {if (true) return new funlhsR1(block, firstToken.next,token);}
      break;
    default:
      jj_la1[37] = jj_gen;
      if (isNot(SEMICOLON,EQUALS)) {
        t = findUntilSemiOrEquals();
                                                                       finduntilsemiorequals=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new funlhsR2(finduntilsemiorequals, firstToken.next,token);}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public varop varop() throws ParseException {
        Token t;
        ASTStringNode varsym;
        ASTStringNode variable_id;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARSYM:
      t = jj_consume_token(VARSYM);
                   varsym=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new varop1(varsym, firstToken.next,token);}
      break;
    case INFIX_QUOTE:
      jj_consume_token(INFIX_QUOTE);
      t = jj_consume_token(VARIABLE_ID);
                            variable_id=new ASTStringNode(t.image,new WToken(t));
      jj_consume_token(INFIX_QUOTE);
         {if (true) return new varop2(variable_id, firstToken.next,token);}
      break;
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public conop conop() throws ParseException {
        Token t;
        ASTStringNode consym;
        ASTStringNode constructor_id;
        Token firstToken=token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSYM:
      t = jj_consume_token(CONSYM);
                   consym=new ASTStringNode(t.image,new WToken(t));
         {if (true) return new conop1(consym, firstToken.next,token);}
      break;
    case INFIX_QUOTE:
      jj_consume_token(INFIX_QUOTE);
      t = jj_consume_token(CONSTRUCTOR_ID);
                               constructor_id=new ASTStringNode(t.image,new WToken(t));
      jj_consume_token(INFIX_QUOTE);
         {if (true) return new conop2(constructor_id, firstToken.next,token);}
      break;
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public op op() throws ParseException {
        varop varop;
        conop conop;
        Token firstToken=token;
    if (jj_2_10(2)) {
      varop = varop();
         {if (true) return new op1(varop, firstToken.next,token);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INFIX_QUOTE:
      case CONSYM:
        conop = conop();
         {if (true) return new op2(conop, firstToken.next,token);}
        break;
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public block block() throws ParseException {
        Token t;
        ASTStringNode findblockcontent = null;
        Token firstToken=token;
    jj_consume_token(LEFT_CURLY);
    if (isNot(RIGHT_CURLY)) {
      t = findBlockContent();
                                                                  findblockcontent=new ASTStringNode(t.image,new WToken(t));
    } else {
      ;
    }
    jj_consume_token(RIGHT_CURLY);
         {if (true) return new block(findblockcontent, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final public list list() throws ParseException {
        Token t;
        ASTStringNode findlistcontent = null;
        Token firstToken=token;
    jj_consume_token(LEFT_PAREN);
    if (isNot(RIGHT_PAREN)) {
      t = findListContent();
                                                                 findlistcontent=new ASTStringNode(t.image,new WToken(t));
    } else {
      ;
    }
    jj_consume_token(RIGHT_PAREN);
         {if (true) return new list(findlistcontent, firstToken.next,token);}
    throw new Error("Missing return statement in function");
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  final private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  final private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  final private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  final private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  final private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  final private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  final private boolean jj_3R_23() {
    return false;
  }

  final private boolean jj_3R_22() {
    if (jj_scan_token(IMPORT)) return true;
    return false;
  }

  final private boolean jj_3R_31() {
    if (jj_scan_token(INFIX_QUOTE)) return true;
    if (jj_scan_token(VARIABLE_ID)) return true;
    if (jj_scan_token(INFIX_QUOTE)) return true;
    return false;
  }

  final private boolean jj_3R_33() {
    if (jj_3R_43()) return true;
    return false;
  }

  final private boolean jj_3R_30() {
    if (jj_scan_token(VARSYM)) return true;
    return false;
  }

  final private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) return true;
    }
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  final private boolean jj_3R_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    return false;
  }

  final private boolean jj_3R_47() {
    if (true) { jj_la = 0; jj_scanpos = jj_lastpos; return false;}
    return false;
  }

  final private boolean jj_3R_46() {
    if (jj_3R_50()) return true;
    return false;
  }

  final private boolean jj_3R_12() {
    if (jj_3R_14()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_4()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3_9() {
    if (jj_scan_token(VARIABLE_ID)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_scan_token(LEFT_PAREN)) return true;
    if (jj_scan_token(VARSYM)) return true;
    return false;
  }

  final private boolean jj_3R_29() {
    if (jj_3R_40()) return true;
    return false;
  }

  final private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    lookingAhead = true;
    jj_semLA = isNot(SEMICOLON,EQUALS);
    lookingAhead = false;
    if (!jj_semLA || jj_3R_47()) return true;
    }
    return false;
  }

  final private boolean jj_3R_39() {
    if (jj_3R_26()) return true;
    return false;
  }

  final private boolean jj_3_3() {
    if (jj_scan_token(LEFT_CURLY)) return true;
    if (jj_3R_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_13()) jj_scanpos = xsp;
    if (jj_scan_token(RIGHT_CURLY)) return true;
    return false;
  }

  final private boolean jj_3R_38() {
    if (jj_scan_token(VARIABLE_ID)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3R_21() {
    if (jj_scan_token(MODULE)) return true;
    return false;
  }

  final private boolean jj_3R_20() {
    if (jj_3R_33()) return true;
    return false;
  }

  final private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) return true;
    }
    return false;
  }

  final private boolean jj_3R_19() {
    if (jj_3R_32()) return true;
    return false;
  }

  final private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_35() {
    if (jj_3R_45()) return true;
    return false;
  }

  final private boolean jj_3R_44() {
    if (jj_scan_token(CONSTRUCTOR_ID)) return true;
    return false;
  }

  final private boolean jj_3R_17() {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_49() {
    if (true) { jj_la = 0; jj_scanpos = jj_lastpos; return false;}
    return false;
  }

  final private boolean jj_3R_27() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  final private boolean jj_3_5() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3R_51() {
    if (true) { jj_la = 0; jj_scanpos = jj_lastpos; return false;}
    return false;
  }

  final private boolean jj_3R_45() {
    if (jj_scan_token(LEFT_PAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) jj_scanpos = xsp;
    if (jj_scan_token(RIGHT_PAREN)) return true;
    return false;
  }

  final private boolean jj_3R_34() {
    if (jj_3R_44()) return true;
    return false;
  }

  final private boolean jj_3R_25() {
    if (jj_3R_34()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_24() {
    if (jj_3R_26()) return true;
    return false;
  }

  final private boolean jj_3R_48() {
    if (jj_scan_token(VARIABLE_ID)) return true;
    return false;
  }

  final private boolean jj_3_4() {
    if (jj_scan_token(SEMICOLON)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_37() {
    if (jj_scan_token(LEFT_PAREN)) return true;
    if (jj_scan_token(VARSYM)) return true;
    if (jj_scan_token(RIGHT_PAREN)) return true;
    return false;
  }

  final private boolean jj_3_8() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(OFTYPE)) return true;
    return false;
  }

  final private boolean jj_3R_50() {
    if (jj_scan_token(LEFT_CURLY)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) jj_scanpos = xsp;
    if (jj_scan_token(RIGHT_CURLY)) return true;
    return false;
  }

  final private boolean jj_3R_43() {
    if (jj_scan_token(CONSTRUCTOR_ID)) return true;
    return false;
  }

  final private boolean jj_3R_42() {
    if (jj_scan_token(LEFT_PAREN)) return true;
    return false;
  }

  final private boolean jj_3R_36() {
    if (jj_scan_token(VARIABLE_ID)) return true;
    return false;
  }

  final private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    return false;
  }

  final private boolean jj_3R_41() {
    if (jj_3R_48()) return true;
    return false;
  }

  final private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    return false;
  }

  final private boolean jj_3_10() {
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3_7() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(EQUALS)) return true;
    return false;
  }

  final private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) return true;
    }
    return false;
  }

  final private boolean jj_3_6() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(OFTYPE)) return true;
    return false;
  }

  final private boolean jj_3R_13() {
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  final private boolean jj_3R_16() {
    if (jj_3R_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_27()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  public HaskellParserTokenManager token_source;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x0,0xc0000002,0x0,0x0,0xc0000002,0xc0000000,0x0,0x0,0xc0000000,0x80000000,0x0,0x0,0x10,0x40,0x80,0x8,0x80,0xc0000000,0x0,0xc0000000,0x0,0x20,0x4,0x4,0x3f00,0xe0000,0x400000,0x80000000,0x40000000,0x0,0x0,0xe0000,0x0,0x0,0x80000000,0x40000000,0x80000000,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x80000,0x80000,0x800000,0x80000,0x80000,0x0,0x80000,0x800000,0x0,0x80000,0x40000,0x10000,0x0,0x0,0x80000,0x0,0x0,0x80000,0x80000,0x80000,0x40000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x280000,0x40000,0x1,0x0,0x800000,0x800000,0x80000,0x80000,0x80000,0x10000,0x3000000,0x5000000,0x5000000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[10];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public HaskellParser(CharStream stream) {
    token_source = new HaskellParserTokenManager(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(CharStream stream) {
    token_source.ReInit(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public HaskellParser(HaskellParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(HaskellParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[62];
    for (int i = 0; i < 62; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 62; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 10; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

  }
