/* Generated By:JavaCC: Do not edit this line. AntLRParserConstants.java */
package tmp.generated_antlr;

public interface AntLRParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int LPAREN = 13;
  int RPAREN = 14;
  int M1 = 15;
  int M2 = 16;
  int M3 = 17;
  int M4 = 18;
  int GR = 19;
  int COMMA = 20;
  int SEMI = 21;
  int DOT = 22;
  int PLUS = 23;
  int STAR = 24;
  int BIT_OR = 25;
  int XOR = 26;
  int TOKEN_REF = 27;
  int RULE_REF = 28;
  int CHAR_LITERAL = 29;
  int STRING_LITERAL = 30;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"(\"",
    "\")\"",
    "\"private\"",
    "\"public\"",
    "\"protected\"",
    "\"fragment\"",
    "\"grammar\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"+\"",
    "\"*\"",
    "\"|\"",
    "\"^\"",
    "<TOKEN_REF>",
    "<RULE_REF>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "\"!\"",
    "\":\"",
    "\"?\"",
  };

}
