/* Generated By:JavaCC: Do not edit this line. DTDParserTokenManager.java */
package tmp.generated_dtd;
import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;
import cide.gparser.*;
public class DTDParserTokenManager implements DTDParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x480200000L) != 0L)
            return 17;
         if ((active0 & 0x7ff00L) != 0L)
         {
            jjmatchedKind = 26;
            return 1;
         }
         return -1;
      case 1:
         if ((active0 & 0x480000000L) != 0L)
            return 16;
         if ((active0 & 0x3800L) != 0L)
            return 1;
         if ((active0 & 0x7c700L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 26;
               jjmatchedPos = 1;
            }
            return 1;
         }
         return -1;
      case 2:
         if ((active0 & 0x7f500L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 2;
            return 1;
         }
         if ((active0 & 0x200L) != 0L)
            return 1;
         return -1;
      case 3:
         if ((active0 & 0x7f500L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 3;
            return 1;
         }
         return -1;
      case 4:
         if ((active0 & 0x7c000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 26;
               jjmatchedPos = 4;
            }
            return 1;
         }
         if ((active0 & 0x3500L) != 0L)
            return 1;
         return -1;
      case 5:
         if ((active0 & 0x78000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 5;
            return 1;
         }
         if ((active0 & 0x6000L) != 0L)
            return 1;
         return -1;
      case 6:
         if ((active0 & 0x48000L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 26;
               jjmatchedPos = 6;
            }
            return 1;
         }
         if ((active0 & 0x30000L) != 0L)
            return 1;
         return -1;
      case 7:
         if ((active0 & 0x68000L) != 0L)
            return 1;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 35:
         return jjMoveStringLiteralDfa1_0(0xf0L);
      case 40:
         return jjStopAtPos(0, 19);
      case 41:
         return jjStopAtPos(0, 20);
      case 42:
         return jjStopAtPos(0, 23);
      case 43:
         return jjStopAtPos(0, 24);
      case 44:
         return jjStopAtPos(0, 33);
      case 60:
         jjmatchedKind = 21;
         return jjMoveStringLiteralDfa1_0(0x480000000L);
      case 62:
         return jjStopAtPos(0, 22);
      case 63:
         return jjStopAtPos(0, 25);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0xc400L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x3800L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x70000L);
      case 124:
         return jjStopAtPos(0, 32);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa2_0(active0, 0x480000000L);
      case 68:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x3100L);
      case 70:
         return jjMoveStringLiteralDfa2_0(active0, 0x10L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x20L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x30400L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0xc200L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000100L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000080L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x10L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x7c000L);
      case 89:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x3000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0xc000L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x30000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 81:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000500L);
      case 88:
         return jjMoveStringLiteralDfa4_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000010L);
      case 70:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 75:
         return jjMoveStringLiteralDfa5_0(active0, 0x30000L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x40004c000L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      case 89:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(5, 4);
         break;
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0x30000L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x480a0L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000L);
      case 77:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000L);
      case 83:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 1);
         break;
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      case 89:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(6, 6);
         break;
      case 69:
         return jjMoveStringLiteralDfa7_0(active0, 0x80008020L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L);
      case 78:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      case 79:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000L);
      case 82:
         return jjMoveStringLiteralDfa7_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(7, 5);
         break;
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0x80L);
      case 78:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 1);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L);
      case 83:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 15, 1);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 17, 1);
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(8, 7);
         break;
      case 84:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(8, 31);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(8, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 21;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 17:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if (curChar == 63)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 0:
                  if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                     jjCheckNAdd(8);
                  }
                  else if (curChar == 60)
                     jjAddStates(0, 1);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(6, 7);
                  else if (curChar == 39)
                     jjCheckNAddTwoStates(3, 4);
                  else if (curChar == 58)
                  {
                     if (kind > 26)
                        kind = 26;
                     jjCheckNAdd(1);
                  }
                  break;
               case 1:
                  if ((0x7ff600000000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 3:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if (curChar == 39 && kind > 27)
                     kind = 27;
                  break;
               case 5:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(6, 7);
                  break;
               case 6:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(6, 7);
                  break;
               case 7:
                  if (curChar == 34 && kind > 27)
                     kind = 27;
                  break;
               case 8:
                  if ((0x100002600L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAdd(8);
                  break;
               case 9:
                  if (curChar == 60)
                     jjAddStates(0, 1);
                  break;
               case 10:
                  if (curChar == 45)
                     jjCheckNAddStates(2, 4);
                  break;
               case 11:
                  if ((0xffffdfffffffffffL & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 12:
                  if (curChar == 45)
                     jjCheckNAdd(11);
                  break;
               case 13:
                  if (curChar == 62 && kind > 29)
                     kind = 29;
                  break;
               case 14:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 18:
                  if (curChar == 63)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 19:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 20:
                  if (curChar == 62 && kind > 30)
                     kind = 30;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAdd(1);
                  break;
               case 3:
                  jjAddStates(5, 6);
                  break;
               case 6:
                  jjAddStates(7, 8);
                  break;
               case 11:
                  jjAddStates(2, 4);
                  break;
               case 19:
                  jjAddStates(9, 10);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(5, 6);
                  break;
               case 6:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(7, 8);
                  break;
               case 11:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(2, 4);
                  break;
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(9, 10);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 21 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   17, 18, 11, 12, 15, 3, 4, 6, 7, 19, 20, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, "\43\106\111\130\105\104", 
"\43\111\115\120\114\111\105\104", "\43\120\103\104\101\124\101", "\43\122\105\121\125\111\122\105\104", 
"\103\104\101\124\101", "\101\116\131", "\105\115\120\124\131", "\111\104", "\111\104\122\105\106", 
"\111\104\122\105\106\123", "\105\116\124\111\124\131", "\105\116\124\111\124\111\105\123", 
"\116\115\124\117\113\105\116", "\116\115\124\117\113\105\116\123", "\116\117\124\101\124\111\117\116", "\50", 
"\51", "\74", "\76", "\52", "\53", "\77", null, null, null, null, null, 
"\74\41\105\114\105\115\105\116\124", "\174", "\54", "\74\41\101\124\124\114\111\123\124", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x78ffffff1L, 
};
static final long[] jjtoSkip = {
   0x70000000L, 
};
protected CharStream input_stream;
private final int[] jjrounds = new int[21];
private final int[] jjstateSet = new int[42];
protected char curChar;
public DTDParserTokenManager(CharStream stream){
   input_stream = stream;
}
public DTDParserTokenManager(CharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(CharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 21; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(CharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   t.offset = input_stream.getOffset();
   t.length = input_stream.getLength();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
