/* Generated By:JavaCC: Do not edit this line. DTDParserConstants.java */
package tmp.generated_dtd;

public interface DTDParserConstants {

  int EOF = 0;
  int LETTER = 1;
  int DIGIT = 2;
  int NAMECHAR = 3;
  int FIXED = 4;
  int IMPLIED = 5;
  int PCDATA = 6;
  int REQUIRED = 7;
  int CDATA = 8;
  int ANY = 9;
  int EMPTY = 10;
  int ID = 11;
  int IDREF = 12;
  int IDREFS = 13;
  int ENTITY = 14;
  int ENTITIES = 15;
  int NMTOKEN = 16;
  int NMTOKENS = 17;
  int NOTATION = 18;
  int OB = 19;
  int CB = 20;
  int POB = 21;
  int PCB = 22;
  int STAR = 23;
  int PLUS = 24;
  int Q = 25;
  int NAME = 26;
  int QUOTEDSTR = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "<NAMECHAR>",
    "\"#FIXED\"",
    "\"#IMPLIED\"",
    "\"#PCDATA\"",
    "\"#REQUIRED\"",
    "\"CDATA\"",
    "\"ANY\"",
    "\"EMPTY\"",
    "\"ID\"",
    "\"IDREF\"",
    "\"IDREFS\"",
    "\"ENTITY\"",
    "\"ENTITIES\"",
    "\"NMTOKEN\"",
    "\"NMTOKENS\"",
    "\"NOTATION\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "<NAME>",
    "<QUOTEDSTR>",
    "<token of kind 28>",
    "<token of kind 29>",
    "<token of kind 30>",
    "\"<!ELEMENT\"",
    "\"|\"",
    "\",\"",
    "\"<!ATTLIST\"",
  };

}
