/* Generated By:JavaCC: Do not edit this line. CPPApproxParserTokenManager.java */
package tmp.generated_cppapprox;
import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;
import cide.gparser.*;
public class CPPApproxParserTokenManager implements CPPApproxParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active1 & 0x100L) != 0L)
            return 7;
         if ((active0 & 0x6000000000000000L) != 0L)
            return 38;
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 75;
            return 65;
         }
         if ((active0 & 0xffff83ffbf80000L) != 0L)
         {
            jjmatchedKind = 75;
            return 140;
         }
         if ((active1 & 0x6c3L) != 0L)
            return 52;
         if ((active0 & 0x7c000000000L) != 0L)
         {
            jjmatchedKind = 75;
            return 114;
         }
         return -1;
      case 1:
         if ((active0 & 0x2000000000000000L) != 0L)
            return 39;
         if ((active0 & 0x880000600000L) != 0L)
            return 140;
         if ((active0 & 0x7c000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return 113;
         }
         if ((active0 & 0xfff703fff980000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return 140;
         }
         return -1;
      case 2:
         if ((active0 & 0x80200000000000L) != 0L)
            return 140;
         if ((active0 & 0xf7f57fffff80000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 2;
            return 140;
         }
         return -1;
      case 3:
         if ((active0 & 0x2100085000000L) != 0L)
            return 140;
         if ((active0 & 0xf7d47ff7af80000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 3;
            return 140;
         }
         return -1;
      case 4:
         if ((active0 & 0x10840042aa00000L) != 0L)
            return 140;
         if ((active0 & 0xe7507fb50580000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 4;
            return 140;
         }
         return -1;
      case 5:
         if ((active0 & 0x41003910500000L) != 0L)
            return 140;
         if ((active0 & 0xe3407c240080000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 5;
            return 140;
         }
         return -1;
      case 6:
         if ((active0 & 0x214000040080000L) != 0L)
            return 140;
         if ((active0 & 0xc2007c200000000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 6;
            return 140;
         }
         return -1;
      case 7:
         if ((active0 & 0xc0000c200000000L) != 0L)
            return 140;
         if ((active0 & 0x20070000000000L) != 0L)
         {
            if (jjmatchedPos != 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return 140;
         }
         return -1;
      case 8:
         if ((active0 & 0x20010000000000L) != 0L)
            return 140;
         if ((active0 & 0x64000000000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 8;
            return 140;
         }
         return -1;
      case 9:
         if ((active0 & 0x4000000000L) != 0L)
            return 140;
         if ((active0 & 0x60000000000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 9;
            return 140;
         }
         return -1;
      case 10:
         if ((active0 & 0x60000000000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 10;
            return 140;
         }
         return -1;
      case 11:
         if ((active0 & 0x20000000000L) != 0L)
            return 140;
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 11;
            return 140;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         return jjStopAtPos(0, 3);
      case 10:
         return jjStopAtPos(0, 1);
      case 13:
         return jjStopAtPos(0, 4);
      case 32:
         return jjStopAtPos(0, 2);
      case 35:
         return jjStartNfaWithStates_0(0, 72, 7);
      case 38:
         return jjStartNfaWithStates_0(0, 74, 52);
      case 40:
         return jjStopAtPos(0, 66);
      case 41:
         return jjStopAtPos(0, 67);
      case 42:
         return jjStartNfaWithStates_0(0, 70, 52);
      case 44:
         return jjStopAtPos(0, 63);
      case 58:
         jjmatchedKind = 62;
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L);
      case 59:
         return jjStopAtPos(0, 60);
      case 60:
         return jjStartNfaWithStates_0(0, 64, 52);
      case 61:
         return jjStartNfaWithStates_0(0, 71, 52);
      case 62:
         return jjStartNfaWithStates_0(0, 65, 52);
      case 95:
         return jjMoveStringLiteralDfa1_0(0x7c000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x10a000400000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x4800000100000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x1001a3800000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x82000680000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x800000000000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x70000010000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1001800000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x480000040000000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x208000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x400000000000L);
      case 123:
         return jjStopAtPos(0, 68);
      case 124:
         return jjStartNfaWithStates_0(0, 73, 52);
      case 125:
         return jjStopAtPos(0, 69);
      default :
         return jjMoveNfa_0(8, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, 0L);
      return 1;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 61, 39);
         break;
      case 95:
         return jjMoveStringLiteralDfa2_0(active0, 0x7c000000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x102000000000000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x404000000100000L);
      case 102:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x600000L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000004000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x8100003000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2288880000L);
      case 111:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 47, 140);
         return jjMoveStringLiteralDfa2_0(active0, 0x200400000000L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0xb0000030000000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, 0L);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000810000000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x8a00000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4040000100000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1140c001000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x404400000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 114:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 45, 140);
         return jjMoveStringLiteralDfa3_0(active0, 0x200011020000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2100202000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000100000000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 121:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 55, 140);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 140);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 140);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 49, 140);
         return jjMoveStringLiteralDfa4_0(active0, 0x10148200000L);
      case 102:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 140);
         break;
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x2202900000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x40400000080000L);
      case 109:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 31, 140);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0xc000000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x40020000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000400000000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x221000800000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 80:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x810000000000000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x1001000000000L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 101:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 46, 140);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000400000L);
      case 102:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 140);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 23, 140);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 25, 140);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 140);
         break;
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x10200000000L);
      case 104:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 56, 140);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000800000000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000c000000000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000100000L);
      case 114:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 140);
         return jjMoveStringLiteralDfa5_0(active0, 0x40100000000L);
      case 115:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 140);
         break;
      case 116:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 140);
         break;
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x204000000080000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      case 97:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 28, 140);
         return jjMoveStringLiteralDfa6_0(active0, 0x600000000000000L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 99:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 35, 140);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 54, 140);
         return jjMoveStringLiteralDfa6_0(active0, 0x20040000000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 20, 140);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 37, 140);
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 102:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 22, 140);
         break;
      case 104:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 48, 140);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0xc000000000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000L);
      case 110:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 140);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L);
      case 116:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 36, 140);
         return jjMoveStringLiteralDfa6_0(active0, 0x810000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 70:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L);
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 140);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 52, 140);
         return jjMoveStringLiteralDfa7_0(active0, 0x40200000000L);
      case 102:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 140);
         break;
      case 108:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 140);
         break;
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0xc000000000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000000L);
      case 116:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 50, 140);
         return jjMoveStringLiteralDfa7_0(active0, 0x420000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 85:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
      case 100:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(7, 33, 140);
         break;
      case 101:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 58, 140);
         return jjMoveStringLiteralDfa8_0(active0, 0x20004000000000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L);
      case 114:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 59, 140);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L);
      case 95:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000L);
      case 100:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 53, 140);
         break;
      case 107:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 40, 140);
         break;
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000L);
      case 95:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 38, 140);
         break;
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private final int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000000L);
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
private final int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 95:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 41, 140);
         break;
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
private final int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 42, 140);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 140;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 7:
               case 52:
                  if ((0xf000ec7a00000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAdd(52);
                  break;
               case 39:
               case 40:
                  if (curChar != 36)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAdd(41);
                  break;
               case 113:
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 38;
                  if ((0x3ff001000000000L & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 140:
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 38;
                  if ((0x3ff001000000000L & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 114:
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 38;
                  if ((0x3ff001000000000L & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 65:
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 38;
                  if ((0x3ff001000000000L & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 8:
                  if ((0xf000ec7a00000000L & l) != 0L)
                  {
                     if (kind > 79)
                        kind = 79;
                     jjCheckNAdd(52);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 38;
                  else if (curChar == 39)
                     jjAddStates(7, 8);
                  else if (curChar == 34)
                     jjCheckNAddStates(9, 11);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAddTwoStates(30, 31);
                  }
                  else if (curChar == 47)
                     jjAddStates(12, 13);
                  else if (curChar == 48)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAddStates(14, 16);
                  }
                  else if (curChar == 36)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAddStates(17, 19);
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(33);
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjAddStates(20, 22);
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 9:
                  if (curChar == 34)
                     jjCheckNAddStates(9, 11);
                  break;
               case 10:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 12:
                  if ((0x8400002400L & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 13:
                  if (curChar == 34 && kind > 10)
                     kind = 10;
                  break;
               case 14:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(23, 26);
                  break;
               case 15:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 16:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(15);
                  break;
               case 18:
                  if (curChar == 10)
                     jjCheckNAddStates(9, 11);
                  break;
               case 19:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 39)
                     jjAddStates(7, 8);
                  break;
               case 21:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(22);
                  break;
               case 22:
                  if (curChar == 39 && kind > 10)
                     kind = 10;
                  break;
               case 24:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(22);
                  break;
               case 25:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(26, 22);
                  break;
               case 26:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(22);
                  break;
               case 27:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(26);
                  break;
               case 29:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(30, 31);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(30, 31);
                  break;
               case 32:
                  if (curChar == 46)
                     jjCheckNAdd(33);
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddStates(27, 29);
                  break;
               case 35:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(36);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(36, 37);
                  break;
               case 38:
                  if (curChar == 58)
                     jjAddStates(30, 32);
                  break;
               case 41:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAdd(41);
                  break;
               case 46:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 51:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 54:
                  if (curChar == 36)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 55:
                  if ((0x3ff001000000000L & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 56:
                  if (curChar != 36)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAddStates(17, 19);
                  break;
               case 62:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 66:
                  if (curChar != 48)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddStates(14, 16);
                  break;
               case 67:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(67, 31);
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(69, 31);
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(33, 35);
                  break;
               case 73:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(74);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(74, 37);
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(75, 76);
                  break;
               case 77:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(78);
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(78, 37);
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(79, 80);
                  break;
               case 80:
                  if (curChar != 46)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddStates(36, 38);
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddStates(36, 38);
                  break;
               case 83:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(84);
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(84, 37);
                  break;
               case 85:
                  if (curChar == 47)
                     jjAddStates(12, 13);
                  break;
               case 86:
                  if (curChar == 47)
                     jjCheckNAddStates(39, 41);
                  break;
               case 87:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(39, 41);
                  break;
               case 88:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 89:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 90:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(92, 93);
                  break;
               case 92:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(92, 93);
                  break;
               case 93:
                  if (curChar == 42)
                     jjCheckNAddStates(42, 44);
                  break;
               case 94:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(95, 93);
                  break;
               case 95:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(95, 93);
                  break;
               case 96:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 98:
                  if (curChar == 40)
                     jjCheckNAddTwoStates(99, 101);
                  break;
               case 99:
                  if ((0xfffffdffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(99, 101);
                  break;
               case 100:
                  if (curChar == 41 && kind > 8)
                     kind = 8;
                  break;
               case 101:
                  if (curChar == 41)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 115:
                  if (curChar == 40)
                     jjCheckNAddTwoStates(116, 119);
                  break;
               case 116:
                  if ((0xfffffdffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(116, 119);
                  break;
               case 117:
                  if (curChar == 41 && kind > 9)
                     kind = 9;
                  break;
               case 118:
                  if (curChar == 41)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 41)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 126:
                  if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 7:
                  if ((0x5000000050000001L & l) != 0L)
                  {
                     if (kind > 79)
                        kind = 79;
                     jjCheckNAdd(52);
                  }
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 39:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  else if (curChar == 126)
                     jjCheckNAdd(40);
                  if (curChar == 108)
                     jjCheckNAdd(49);
                  break;
               case 113:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 137;
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 140:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 114:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 138;
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 65:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAdd(41);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 48;
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 8:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAddStates(17, 19);
                  }
                  else if ((0x5000000050000001L & l) != 0L)
                  {
                     if (kind > 79)
                        kind = 79;
                     jjCheckNAdd(52);
                  }
                  if (curChar == 95)
                     jjAddStates(45, 46);
                  else if (curChar == 108)
                     jjCheckNAddTwoStates(65, 49);
                  else if (curChar == 126)
                     jjCheckNAddTwoStates(54, 40);
                  break;
               case 0:
                  if (curChar == 101)
                     jjCheckNAddStates(20, 22);
                  break;
               case 1:
                  jjCheckNAddStates(20, 22);
                  break;
               case 5:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 6:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 10:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 11:
                  if (curChar == 92)
                     jjAddStates(47, 50);
                  break;
               case 12:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 21:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(22);
                  break;
               case 23:
                  if (curChar == 92)
                     jjAddStates(51, 53);
                  break;
               case 24:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(22);
                  break;
               case 31:
                  if ((0x100000001000L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 34:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(54, 55);
                  break;
               case 37:
                  if ((0x5000000050L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 40:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAdd(41);
                  break;
               case 41:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAdd(41);
                  break;
               case 42:
                  if (curChar == 103 && kind > 75)
                     kind = 75;
                  break;
               case 43:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 47:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 108)
                     jjCheckNAdd(49);
                  break;
               case 52:
                  if ((0x5000000050000001L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAdd(52);
                  break;
               case 53:
                  if (curChar == 126)
                     jjCheckNAddTwoStates(54, 40);
                  break;
               case 54:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 55:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(55, 51);
                  break;
               case 56:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAddStates(17, 19);
                  break;
               case 57:
                  if (curChar == 108)
                     jjCheckNAddTwoStates(65, 49);
                  break;
               case 58:
                  if (curChar == 103)
                     jjCheckNAdd(51);
                  break;
               case 59:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 63:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 68:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(69);
                  break;
               case 69:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(69, 31);
                  break;
               case 72:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(56, 57);
                  break;
               case 76:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(58, 59);
                  break;
               case 82:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(60, 61);
                  break;
               case 87:
                  jjAddStates(39, 41);
                  break;
               case 92:
                  jjCheckNAddTwoStates(92, 93);
                  break;
               case 94:
               case 95:
                  jjCheckNAddTwoStates(95, 93);
                  break;
               case 97:
                  if (curChar == 95)
                     jjAddStates(45, 46);
                  break;
               case 99:
                  jjAddStates(62, 63);
                  break;
               case 103:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 116:
                  jjAddStates(64, 65);
                  break;
               case 120:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 121:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 128:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(20, 22);
                  break;
               case 10:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(9, 11);
                  break;
               case 21:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 87:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(39, 41);
                  break;
               case 92:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(92, 93);
                  break;
               case 94:
               case 95:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(95, 93);
                  break;
               case 99:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(62, 63);
                  break;
               case 116:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(64, 65);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 140 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   71, 72, 37, 75, 76, 79, 80, 21, 23, 10, 11, 13, 86, 91, 67, 31, 
   68, 55, 51, 41, 1, 2, 4, 10, 11, 15, 13, 33, 34, 37, 39, 40, 
   50, 71, 72, 37, 81, 82, 37, 87, 88, 90, 93, 94, 96, 114, 139, 12, 
   14, 16, 19, 24, 25, 27, 35, 36, 73, 74, 77, 78, 83, 84, 99, 101, 
   116, 119, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, "\151\156\143\154\165\144\145", 
"\144\145\146\151\156\145", "\151\146\144\145\146", "\151\146\156\144\145\146", "\145\156\144\151\146", 
"\145\154\151\146", "\145\154\163\151\146", "\154\151\156\145", "\165\156\144\145\146", 
"\160\162\141\147\155\141", "\145\162\162\157\162", "\164\171\160\145\144\145\146", "\145\156\165\155", 
"\145\170\164\145\162\156", "\165\156\163\151\147\156\145\144", "\143\157\156\163\164", 
"\163\164\141\164\151\143", "\163\164\162\165\143\164", "\151\156\154\151\156\145", 
"\137\137\151\156\154\151\156\145\137\137", "\137\137\151\156\154\151\156\145", "\137\137\162\145\147\142\141\156\153", 
"\137\137\124\111\120\117\106\125\116\103\137\137", "\137\137\146\157\162\143\145\151\156\154\151\156\145", "\151\146", 
"\145\154\163\145", "\146\157\162", "\167\150\151\154\145", "\144\157", 
"\163\167\151\164\143\150", "\143\141\163\145", "\144\145\146\141\165\154\164", "\143\154\141\163\163", 
"\160\162\151\166\141\164\145", "\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", 
"\164\162\171", "\143\141\164\143\150", "\166\151\162\164\165\141\154", 
"\164\145\155\160\154\141\164\145", "\157\160\145\162\141\164\157\162", "\73", "\72\72", "\72", "\54", "\74", 
"\76", "\50", "\51", "\173", "\175", "\52", "\75", "\43", "\174", "\46", null, null, 
null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xfffffffffff80401L, 0x28fffL, 
};
static final long[] jjtoSkip = {
   0x3feL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x3feL, 0x0L, 
};
protected CharStream input_stream;
private final int[] jjrounds = new int[140];
private final int[] jjstateSet = new int[280];
protected char curChar;
public CPPApproxParserTokenManager(CharStream stream){
   input_stream = stream;
}
public CPPApproxParserTokenManager(CharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(CharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 140; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(CharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   t.length = input_stream.getLength();
   t.offset = input_stream.getOffset();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 81)
   {
      jjmatchedKind = 81;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
