/* Generated By:JavaCC: Do not edit this line. PropertyParserConstants.java */
package tmp.generated_property;

public interface PropertyParserConstants {

  int EOF = 0;
  int LINE = 1;
  int NEWLINE = 2;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<LINE>",
    "<NEWLINE>",
  };

}
