/* Generated By:JavaCC: Do not edit this line. BaliParserConstants.java */
package tmp.generated_bali;

public interface BaliParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int LETTER = 13;
  int DIGIT = 14;
  int CLOSEANGLE = 15;
  int CLOSEPAREN = 16;
  int LBRACE = 17;
  int OPENANGLE = 18;
  int OPENPAREN = 19;
  int RBRACE = 20;
  int DOUBLECOLON = 21;
  int COLON = 22;
  int HASH = 23;
  int STAR = 24;
  int PLUS = 25;
  int COMMA = 26;
  int SCOLON = 27;
  int SBOPEN = 28;
  int SBCLOSE = 29;
  int PIPE = 30;
  int _CODE = 31;
  int _EOF = 32;
  int _IGNORE_CASE = 33;
  int _JAVACODE = 34;
  int _LOOKAHEAD = 35;
  int _MORE = 36;
  int _OPTIONS = 37;
  int _PARSER_BEGIN = 38;
  int _PARSER_END = 39;
  int _SKIP = 40;
  int _SPECIAL_TOKEN = 41;
  int _TOKEN = 42;
  int _TOKEN_MGR_DECLS = 43;
  int BALI_TOKEN = 44;
  int UPPERCASE = 45;
  int STRING = 46;
  int INTEGER = 47;
  int IDENTIFIER = 48;
  int OTHER = 49;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<LETTER>",
    "<DIGIT>",
    "\">\"",
    "\")\"",
    "\"{\"",
    "\"<\"",
    "\"(\"",
    "\"}\"",
    "\"::\"",
    "\":\"",
    "\"#\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"code\"",
    "\"EOF\"",
    "\"IGNORE_CASE\"",
    "\"JAVACODE\"",
    "\"LOOKAHEAD\"",
    "\"MORE\"",
    "\"options\"",
    "\"PARSER_BEGIN\"",
    "\"PARSER_END\"",
    "\"SKIP\"",
    "\"SPECIAL_TOKEN\"",
    "\"TOKEN\"",
    "\"TOKEN_MGR_DECLS\"",
    "<BALI_TOKEN>",
    "<UPPERCASE>",
    "<STRING>",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<OTHER>",
  };

}
